CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(200) NOT NULL,
    price       BIGINT       NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT chk_products_price_non_negative CHECK (price >= 0)
);
