CREATE TABLE categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    parent_id  BIGINT,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE INDEX idx_categories_parent_id
    ON categories (parent_id);

ALTER TABLE products
    ADD COLUMN category_id BIGINT;

INSERT INTO categories (name, parent_id, created_at, updated_at)
SELECT '미분류', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE EXISTS (SELECT 1 FROM products);

UPDATE products
SET category_id = (
    SELECT id
    FROM categories
    WHERE name = '미분류'
      AND parent_id IS NULL
    ORDER BY id
    LIMIT 1
)
WHERE category_id IS NULL;

ALTER TABLE products
    ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (id);

CREATE INDEX idx_products_category_id
    ON products (category_id);
