ALTER TABLE products
    ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'STOP_SALE';

ALTER TABLE products
    ALTER COLUMN status DROP DEFAULT;

CREATE TABLE product_options
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id       BIGINT       NOT NULL,
    name             VARCHAR(100) NOT NULL,
    additional_price BIGINT       NOT NULL,
    stock            INTEGER      NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_product_options PRIMARY KEY (id),
    CONSTRAINT fk_product_options_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_product_options_additional_price_non_negative
        CHECK (additional_price >= 0),
    CONSTRAINT chk_product_options_stock_non_negative
        CHECK (stock >= 0),
    CONSTRAINT uk_product_options_product_name
        UNIQUE (product_id, name)
);

CREATE INDEX idx_product_options_product_id
    ON product_options (product_id);
